/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Image = string
export type AlternativeText = string
export type ColorOverlay = 'black' | 'maroon' | 'darkGrey'
export type Image1 = string
export type AlternativeText1 = string
export type Heading = string
export type Copy = string
export type Text = string
export type URL = string
export type Color =
  | 'default'
  | 'neutralDark'
  | 'neutralLight'
  | 'naked'
  | 'important'
export type Size = 'small' | 'medium' | 'large'
/**
 * Select "Eager" when this section appears above the fold.
 */
export type ImageLoadingStrategy = 'lazy' | 'eager'

/**
 * Banner displayed on home page
 */
export interface Banner {
  backgroundImage: BackgroundImage
  colorOverlay: ColorOverlay
  taglineImage: TaglineImage
  heading?: Heading
  copy?: Copy
  cta: CallToAction
  imageLoadingStrategy: ImageLoadingStrategy
  [k: string]: unknown
}
export interface BackgroundImage {
  src: Image
  alt?: AlternativeText
  [k: string]: unknown
}
export interface TaglineImage {
  src: Image1
  alt?: AlternativeText1
  [k: string]: unknown
}
export interface CallToAction {
  text?: Text
  url: URL
  color: Color
  size: Size
  [k: string]: unknown
}
