/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Heading = string
/**
 * @maxItems 1
 */
export type Categories = [] | [Category]
export type Name = string

/**
 * List of all brand links
 */
export interface BrandList {
  heading: Heading
  categories: Categories
  [k: string]: unknown
}
/**
 * Include brands from this category.
 */
export interface Category {
  name: Name
  [k: string]: unknown
}
