/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type IncludeHomeLink = boolean
/**
 * @minItems 1
 * @maxItems 5
 */
export type Links =
  | [Link]
  | [Link, Link]
  | [Link, Link, Link]
  | [Link, Link, Link, Link]
  | [Link, Link, Link, Link, Link]
export type Text = string
export type URL = string

/**
 * Manually enter breadcrumbs for landing page templates.
 */
export interface BreadcrumbManualEntry {
  showHomeLink?: IncludeHomeLink
  links?: Links
  [k: string]: unknown
}
export interface Link {
  name: Text
  item: URL
  [k: string]: unknown
}
