/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ActionLink = string
export type ActionText = string
export type ChoseTextAlignment =
  | 'start'
  | 'left'
  | 'right'
  | 'center'
  | 'justify'
  | 'match-parent'
export type Font = string
export type HrefTag = string
export type Image1 = string
export type AltTag = string
export type Text = string
export type BorderGap = string
export type HasBorderOnListCard = boolean
export type ImageRadius = string
export type ImageWidth = string
export type CardSize = string
export type MarginOfListContainer = string
export type TextColor = string

/**
 * Card in pages
 */
export interface Card {
  actionLink?: ActionLink
  actionText?: ActionText
  textAlignment: TextAlignment
  font?: Font
  href?: HrefTag
  image: Image
  text?: Text
  borderGap?: BorderGap
  hasBorder?: HasBorderOnListCard
  imageRadius?: ImageRadius
  imageWidth?: ImageWidth
  cardSize?: CardSize
  listContainerMargin?: MarginOfListContainer
  textColor?: TextColor
  [k: string]: unknown
}
/**
 * Text Alignment Options
 */
export interface TextAlignment {
  sort: ChoseTextAlignment
  [k: string]: unknown
}
export interface Image {
  src?: Image1
  alt?: AltTag
  [k: string]: unknown
}
