/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type TaxAndDeliveryMessage = string
export type PriceMessage = string
export type TextLoggedIn = string
export type TextLoggedOut = string
export type Text = string
export type Text1 = string
export type URL = string
export type Text2 = string
export type URL1 = string
export type OpenLinkInNewTab = boolean
export type Text3 = string
export type URL2 = string
export type OpenLinkInNewTab1 = boolean
export type AdditionalLinks = Link[]

/**
 * Cart details to display on the cart page
 */
export interface CartDetails {
  messages?: Messages
  ctas: CTAs
  additionalLinks?: AdditionalLinks
  [k: string]: unknown
}
export interface Messages {
  taxDelivery?: TaxAndDeliveryMessage
  price?: PriceMessage
  [k: string]: unknown
}
export interface CTAs {
  checkoutButton: CheckoutButton
  createAccountLink: CreateAccountLink
  continueShoppingButton: ContinueShoppingButton
  quotesLink: QuotesLink
  [k: string]: unknown
}
export interface CheckoutButton {
  textLoggedIn: TextLoggedIn
  textLoggedOut: TextLoggedOut
  [k: string]: unknown
}
export interface CreateAccountLink {
  text: Text
  [k: string]: unknown
}
export interface ContinueShoppingButton {
  text: Text1
  url: URL
  [k: string]: unknown
}
export interface QuotesLink {
  text: Text2
  url: URL1
  newTab: OpenLinkInNewTab
  [k: string]: unknown
}
export interface Link {
  text: Text3
  url: URL2
  newTab: OpenLinkInNewTab1
  [k: string]: unknown
}
