/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type TaxAndDeliveryMessage = string
export type PriceMessage = string
export type Text = string
export type URL = string
export type TextLoggedIn = string
export type TextLoggedOut = string
export type Text1 = string
export type Text2 = string

/**
 * Global cart drawer that opens when adding to cart.
 */
export interface CartDrawer {
  messages?: Messages
  ctas: CTAs
  [k: string]: unknown
}
export interface Messages {
  taxDelivery?: TaxAndDeliveryMessage
  price?: PriceMessage
  [k: string]: unknown
}
export interface CTAs {
  cartButton: CartButton
  checkoutButton: CheckoutButton
  createAccountLink: CreateAccountLink
  continueShoppingLink: ContinueShoppingLink
  [k: string]: unknown
}
export interface CartButton {
  text: Text
  url: URL
  [k: string]: unknown
}
export interface CheckoutButton {
  textLoggedIn: TextLoggedIn
  textLoggedOut: TextLoggedOut
  [k: string]: unknown
}
export interface CreateAccountLink {
  text: Text1
  [k: string]: unknown
}
export interface ContinueShoppingLink {
  text: Text2
  [k: string]: unknown
}
