/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type HeadingText = string
/**
 * @minItems 1
 */
export type Items = [Item, ...Item[]]
export type Image1 = string
export type AlternativeText = string
export type Text = string
export type URL = string
/**
 * Select "Eager" when this section appears above the fold.
 */
export type ImageLoadingStrategy = 'lazy' | 'eager'

/**
 * Circles Grid displayed on home page
 */
export interface CirclesGrid {
  headingText?: HeadingText
  items: Items
  imageLoadingStrategy: ImageLoadingStrategy
  [k: string]: unknown
}
export interface Item {
  image: Image
  text?: Text
  url: URL
  [k: string]: unknown
}
export interface Image {
  src: Image1
  alt?: AlternativeText
  [k: string]: unknown
}
