/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type APIEndpointForAllComposers = string

/**
 * Listing page for all composers with filtering/searching
 */
export interface ComposersList {
  endpoint: APIEndpointForAllComposers
  [k: string]: unknown
}
