/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type IDOfTheTemplateYouWantToRender = string
export type BusinessIDConnectedToTrustpilot = string
export type NumberOfStarsYouWantToFilterOptional = string
export type LanguageOfReviewsYouWantToFilterOptional = string
export type TemplateTheme = string
export type WidthThatTheComponentMustHave = string
export type HeightThatTheComponentMustHave = string
export type FilterByLocationOptional = string
export type IDOfTheTemplateYouWantToRender1 = string
export type BusinessIDConnectedToTrustpilot1 = string
export type NumberOfStarsYouWantToFilterOptional1 = string
export type LanguageOfReviewsYouWantToFilterOptional1 = string
export type TemplateTheme1 = string
export type WidthThatTheComponentMustHave1 = string
export type HeightThatTheComponentMustHave1 = string
export type FilterByLocationOptional1 = string

/**
 * Custom product details to display on PDP
 */
export interface CustomProductDetails {
  trustPilotPdpConfig?: TrustPilotPDPRatingsConfig
  [k: string]: unknown
}
export interface TrustPilotPDPRatingsConfig {
  stars?: TrustPilotStarsConfig
  accordion?: TrustPilotAccordionConfig
  [k: string]: unknown
}
export interface TrustPilotStarsConfig {
  templateId?: IDOfTheTemplateYouWantToRender
  businessId?: BusinessIDConnectedToTrustpilot
  stars?: NumberOfStarsYouWantToFilterOptional
  reviewLanguages?: LanguageOfReviewsYouWantToFilterOptional
  theme?: TemplateTheme
  width?: WidthThatTheComponentMustHave
  height?: HeightThatTheComponentMustHave
  locale?: FilterByLocationOptional
  [k: string]: unknown
}
export interface TrustPilotAccordionConfig {
  templateId?: IDOfTheTemplateYouWantToRender1
  businessId?: BusinessIDConnectedToTrustpilot1
  stars?: NumberOfStarsYouWantToFilterOptional1
  reviewLanguages?: LanguageOfReviewsYouWantToFilterOptional1
  theme?: TemplateTheme1
  width?: WidthThatTheComponentMustHave1
  height?: HeightThatTheComponentMustHave1
  locale?: FilterByLocationOptional1
  [k: string]: unknown
}
