/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Heading = string
export type SearchTermOptional = string
/**
 * Tip: For categories, use: category-{level}. For collections, use: productClusterIds.
 */
export type Key = string
/**
 * Tip: For categories, use: id. For collections, use: id
 */
export type Value = string
export type Facets = Facet[]

/**
 * Add custom product gallery with rules to your store
 */
export interface CustomProductGalleryWithRules {
  heading?: Heading
  productQuery?: Products
  [k: string]: unknown
}
export interface Products {
  term?: SearchTermOptional
  selectedFacets?: Facets
  [k: string]: unknown
}
export interface Facet {
  key: Key
  value: Value
  [k: string]: unknown
}
