/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type IDOfTheTemplateYouWantToRender = string
export type BusinessIDConnectedToTrustpilot = string
export type NumberOfStarsYouWantToFilterOptional = string
export type LanguageOfReviewsYouWantToFilterOptional = string
export type TemplateTheme = string
export type WidthThatTheComponentMustHave = string
export type HeightThatTheComponentMustHave = string
export type FilterByLocationOptional = string

/**
 * Custom product gallery to display on PLP and Search
 */
export interface CustomProductGallery {
  trustPilotPlpConfig?: TrustPilotStarsConfig
  [k: string]: unknown
}
export interface TrustPilotStarsConfig {
  templateId?: IDOfTheTemplateYouWantToRender
  businessId?: BusinessIDConnectedToTrustpilot
  stars?: NumberOfStarsYouWantToFilterOptional
  reviewLanguages?: LanguageOfReviewsYouWantToFilterOptional
  theme?: TemplateTheme
  width?: WidthThatTheComponentMustHave
  height?: HeightThatTheComponentMustHave
  locale?: FilterByLocationOptional
  [k: string]: unknown
}
