/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * @maxItems 4
 */
export type FooterLinksSections =
  | []
  | [FooterLinksSection]
  | [FooterLinksSection, FooterLinksSection]
  | [FooterLinksSection, FooterLinksSection, FooterLinksSection]
  | [
      FooterLinksSection,
      FooterLinksSection,
      FooterLinksSection,
      FooterLinksSection,
    ]
export type SectionTitle = string
/**
 * @minItems 1
 * @maxItems 8
 */
export type Links =
  | [Link]
  | [Link, Link]
  | [Link, Link, Link]
  | [Link, Link, Link, Link]
  | [Link, Link, Link, Link, Link]
  | [Link, Link, Link, Link, Link, Link]
  | [Link, Link, Link, Link, Link, Link, Link]
  | [Link, Link, Link, Link, Link, Link, Link, Link]
export type LinkText = string
/**
 * Absolute or Relative
 */
export type LinkURL = string
export type Title = string
/**
 * @minItems 0
 * @maxItems 8
 */
export type SocialMedia =
  | []
  | [Link1]
  | [Link1, Link1]
  | [Link1, Link1, Link1]
  | [Link1, Link1, Link1, Link1]
  | [Link1, Link1, Link1, Link1, Link1]
  | [Link1, Link1, Link1, Link1, Link1, Link1]
  | [Link1, Link1, Link1, Link1, Link1, Link1, Link1]
  | [Link1, Link1, Link1, Link1, Link1, Link1, Link1, Link1]
export type Icon1 = 'Facebook' | 'Instagram' | 'Youtube' | 'X' | 'Linkedin'
export type Alt = string
export type URL = string
/**
 * Leave empty for gradient
 */
export type Image = string
export type Image1 = string
export type AlternativeLabel = string
export type Tagline = string
export type LinkURL1 = string
export type LinkTitle = string
export type CopyrightMessage = string

/**
 * Custom footer displayed on all pages
 */
export interface CustomFooter {
  footerLinks: FooterLinksSections
  footerSocial: SocialMediaLinks
  background?: Background
  logo: Logo
  copyrightInfo: CopyrightMessage
  [k: string]: unknown
}
export interface FooterLinksSection {
  sectionTitle?: SectionTitle
  items: Links
  [k: string]: unknown
}
export interface Link {
  text: LinkText
  url: LinkURL
  [k: string]: unknown
}
export interface SocialMediaLinks {
  title?: Title
  socialLinks: SocialMedia
  [k: string]: unknown
}
export interface Link1 {
  icon: Icon
  alt: Alt
  url: URL
  [k: string]: unknown
}
export interface Icon {
  icon?: Icon1
  [k: string]: unknown
}
export interface Background {
  image?: Image
  [k: string]: unknown
}
export interface Logo {
  src: Image1
  alt: AlternativeLabel
  tagline?: Tagline
  link?: LogoLink
  [k: string]: unknown
}
export interface LogoLink {
  url: LinkURL1
  title: LinkTitle
  [k: string]: unknown
}
