/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * ID of the parent category in the navigation tree to display.
 */
export type CategoryID = string
/**
 * ID of the subcategory to exclude from nav.
 */
export type ID = string
export type ExcludedSubcategories = ID[]
export type Section = ProductList | TwoCards | ImageAndText
export type Heading = string
export type Text = string
export type URL = string
export type Color =
  | 'default'
  | 'neutralDark'
  | 'neutralLight'
  | 'naked'
  | 'important'
export type ProductCount = 5 | 10
export type Sort =
  | 'discount_desc'
  | 'name_asc'
  | 'name_desc'
  | 'orders_desc'
  | 'price_asc'
  | 'price_desc'
  | 'release_desc'
  | 'score_desc'
export type SearchTermOptional = string
/**
 * Tip: For categories, use: category-{level}. For collections, use: productClusterIds.
 */
export type Key = string
/**
 * Tip: For categories, use: id. For collections, use: id
 */
export type Value = string
/**
 * @minItems 2
 * @maxItems 2
 */
export type TwoCards = [Card, Card]
/**
 * Image dimensions
 */
export type Image1 = string
export type AlternativeText = string
export type Heading1 = string
export type Copy = string
export type URL1 = string
export type Image3 = string
export type AlternativeText1 = string
export type ImagePosition = 'left' | 'right'
export type Date = string
export type Author = string
export type Heading2 = string
export type Copy1 = string
/**
 * Please use either a hex code or an rgb value
 */
export type TextColor = string
/**
 * @minItems 1
 * @maxItems 2
 */
export type CTAs = [CTA] | [CTA, CTA]
export type Text1 = string
export type URL2 = string
export type Color1 =
  | 'default'
  | 'neutralDark'
  | 'neutralLight'
  | 'naked'
  | 'important'
export type Size = 'small' | 'medium' | 'large'
export type ContentSections = Section[]

export interface DepartmentLandingPage {
  sidebarNav: SidebarNav
  contentSections: ContentSections
  [k: string]: unknown
}
export interface SidebarNav {
  departmentId: CategoryID
  excludeIds?: ExcludedSubcategories
  [k: string]: unknown
}
export interface ProductList {
  heading: Heading
  cta: CallToAction
  productQuery: Products
  [k: string]: unknown
}
export interface CallToAction {
  text: Text
  url: URL
  color: Color
  [k: string]: unknown
}
export interface Products {
  first: ProductCount
  sort: Sort
  term?: SearchTermOptional
  selectedFacets?: Facet[]
  [k: string]: unknown
}
export interface Facet {
  key: Key
  value: Value
  [k: string]: unknown
}
export interface Card {
  image: Image
  heading: Heading1
  copy: Copy
  url: URL1
  [k: string]: unknown
}
export interface Image {
  src: Image1
  alt: AlternativeText
  [k: string]: unknown
}
/**
 * Image and Text displayed home page
 */
export interface ImageAndText {
  image: Image2
  content: Content
  [k: string]: unknown
}
export interface Image2 {
  src: Image3
  alt: AlternativeText1
  imagePosition: ImagePosition
  [k: string]: unknown
}
export interface Content {
  date?: Date
  author?: Author
  heading?: Heading2
  copy?: Copy1
  textColor?: TextColor
  ctas: CTAs
  [k: string]: unknown
}
export interface CTA {
  text: Text1
  url: URL2
  color: Color1
  size: Size
  [k: string]: unknown
}
