/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Heading = string
export type Image = string
export type ImageAltText = string
export type Text = string
export type URL = string
/**
 * Select "Eager" when this section appears above the fold.
 */
export type ImageLoadingStrategy = 'lazy' | 'eager'

export interface DepartmentBanner {
  heading?: Heading
  /**
   * @minItems 0
   * @maxItems 4
   */
  links?:
    | []
    | [Link]
    | [Link, Link]
    | [Link, Link, Link]
    | [Link, Link, Link, Link]
  imageLoadingStrategy: ImageLoadingStrategy
  [k: string]: unknown
}
export interface Link {
  imageSrc: Image
  imageAlt: ImageAltText
  text: Text
  url: URL
  [k: string]: unknown
}
