/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ListHeading = string
/**
 * @minItems 1
 */
export type Collections = [Collection, ...Collection[]]
export type CollectionName = string
export type CollectionURL = string
export type CollectionID = string

/**
 * View and Listen list for Editors Choice page
 */
export interface EditorsChoiceViewListenList {
  listHeading: ListHeading
  collections: Collections
  [k: string]: unknown
}
export interface Collection {
  collectionName: CollectionName
  collectionUrl: CollectionURL
  collectionId: CollectionID
  [k: string]: unknown
}
