/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Image = string
export type AlternativeText = string
export type ColorOverlay = 'black' | 'maroon' | 'darkGrey'
export type Image1 = string
export type AlternativeText1 = string
export type Heading = string
export type Copy = string

/**
 * Header banner for the Editors Choice page
 */
export interface EditorsChoiceBanner {
  backgroundImage: BackgroundImage
  colorOverlay: ColorOverlay
  icon: Icon
  heading: Heading
  copy: Copy
  [k: string]: unknown
}
export interface BackgroundImage {
  src: Image
  alt?: AlternativeText
  [k: string]: unknown
}
export interface Icon {
  src: Image1
  alt?: AlternativeText1
  [k: string]: unknown
}
