/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Heading = string
/**
 * @minItems 1
 */
export type YearButtons = [YearButton, ...YearButton[]]
export type Text = string
/**
 * @minItems 1
 */
export type Cards = [Card, ...Card[]]
export type Image = string
export type AlternativeText = string
export type Heading1 = string
export type LinkText = string
export type Link = string
/**
 * Used for sorting only, not displayed
 */
export type Year = string
export type Image1 = string
export type AlternativeText1 = string
export type Image2 = string
export type AlternativeText2 = string

/**
 * Grid of Editors Choice products
 */
export interface EditorsChoiceGrid {
  heading: Heading
  yearButtons: YearButtons
  cards: Cards
  [k: string]: unknown
}
export interface YearButton {
  text: Text
  [k: string]: unknown
}
export interface Card {
  icon: Icon
  heading: Heading1
  linkText: LinkText
  link: Link
  year: Year
  baseImage: BaseImage
  hoverImage: HoverImage
  [k: string]: unknown
}
export interface Icon {
  src: Image
  alt?: AlternativeText
  [k: string]: unknown
}
export interface BaseImage {
  src: Image1
  alt?: AlternativeText1
  [k: string]: unknown
}
export interface HoverImage {
  src: Image2
  alt?: AlternativeText2
  [k: string]: unknown
}
