/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Image = string
export type AlternativeText = string
export type Heading = string

/**
 * Header for Editors Choice page
 */
export interface EditorsChoiceHeader {
  icon: Icon
  heading: Heading
  [k: string]: unknown
}
export interface Icon {
  src: Image
  alt?: AlternativeText
  [k: string]: unknown
}
