/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Image = string
export type AlternativeLabel = string
/**
 * @maxItems 8
 */
export type UtilityNavigationLinks =
  | []
  | [Link]
  | [Link, Link]
  | [Link, Link, Link]
  | [Link, Link, Link, Link]
  | [Link, Link, Link, Link, Link]
  | [Link, Link, Link, Link, Link, Link]
  | [Link, Link, Link, Link, Link, Link, Link]
  | [Link, Link, Link, Link, Link, Link, Link, Link]
export type Icon = string
export type LinkText = string
export type LinkURL = string
export type ShowOnMobileOnly = boolean
export type Message = string
export type SortResultsBy =
  | 'price_desc'
  | 'price_asc'
  | 'orders_desc'
  | 'name_asc'
  | 'name_desc'
  | 'release_desc'
  | 'discount_desc'
  | 'score_desc'
export type CartURL = string
export type LinkText1 = string
export type LinkURL1 = string
export type AccountDropdownLinks = Link1[]

/**
 * Header displayed on all pages
 */
export interface Header {
  logo: Logo
  utilityNavLinks?: UtilityNavigationLinks
  contact: Contact
  searchInput: SearchInput
  cart: Cart
  accountDropdown?: AccountDropdownLinks
  [k: string]: unknown
}
export interface Logo {
  src: Image
  alt: AlternativeLabel
  [k: string]: unknown
}
export interface Link {
  icon?: Icon
  text: LinkText
  url: LinkURL
  mobileOnly: ShowOnMobileOnly
  [k: string]: unknown
}
export interface Contact {
  message: Message
  [k: string]: unknown
}
/**
 * Search Input configurations
 */
export interface SearchInput {
  sort: SortResultsBy
  [k: string]: unknown
}
export interface Cart {
  url: CartURL
  [k: string]: unknown
}
export interface Link1 {
  text: LinkText1
  url: LinkURL1
  [k: string]: unknown
}
