/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * @minItems 1
 * @maxItems 4
 */
export type Slides =
  | [Slide]
  | [Slide, Slide]
  | [Slide, Slide, Slide]
  | [Slide, Slide, Slide, Slide]
export type Image = string
export type AlternativeText = string
export type ColorOverlay = 'black' | 'maroon' | 'darkGrey'
export type Heading = string
export type Copy = string
/**
 * @minItems 1
 * @maxItems 3
 */
export type CallToActions =
  | [CallToAction]
  | [CallToAction, CallToAction]
  | [CallToAction, CallToAction, CallToAction]
export type Text = string
export type URL = string
export type Color =
  | 'default'
  | 'neutralDark'
  | 'neutralLight'
  | 'naked'
  | 'important'
export type Size = 'small' | 'medium' | 'large'
/**
 * Select "Eager" when this section appears above the fold.
 */
export type ImageLoadingStrategy = 'lazy' | 'eager'

/**
 * Hero Carousel displayed on home page
 */
export interface HeroCarousel {
  slides: Slides
  imageLoadingStrategy: ImageLoadingStrategy
  [k: string]: unknown
}
export interface Slide {
  backgroundImage: BackgroundImage
  colorOverlay: ColorOverlay
  heading?: Heading
  copy?: Copy
  ctas: CallToActions
  [k: string]: unknown
}
export interface BackgroundImage {
  src: Image
  alt?: AlternativeText
  [k: string]: unknown
}
export interface CallToAction {
  text?: Text
  url: URL
  color: Color
  size: Size
  [k: string]: unknown
}
