/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Image1 = string
export type AlternativeText = string
export type ImagePosition = 'left' | 'right'
export type Date = string
export type Author = string
export type Heading = string
export type Copy = string
/**
 * Please use either a hex code or an rgb value
 */
export type TextColor = string
/**
 * @minItems 1
 * @maxItems 2
 */
export type CTAs = [CTA] | [CTA, CTA]
export type Text = string
export type URL = string
export type Color =
  | 'default'
  | 'neutralDark'
  | 'neutralLight'
  | 'naked'
  | 'important'
export type Size = 'small' | 'medium' | 'large'
/**
 * Please use either a hex code or an rgb value
 */
export type BackgroundColor = string
export type BackgroundImage = string
export type BackgroundImageDesktopPositionX = 'left' | 'center' | 'right'
export type BackgroundImageDesktopPositionY = 'top' | 'center' | 'bottom'
export type BackgroundImageMobilePositionX = 'left' | 'center' | 'right'
export type BackgroundImageMobilePositionY = 'top' | 'center' | 'bottom'
/**
 * Select "Eager" when this section appears above the fold.
 */
export type ImageLoadingStrategy = 'lazy' | 'eager'

/**
 * Image and Text displayed home page
 */
export interface ImageAndText {
  image: Image
  content: Content
  imageLoadingStrategy: ImageLoadingStrategy
  [k: string]: unknown
}
export interface Image {
  src: Image1
  alt: AlternativeText
  imagePosition: ImagePosition
  [k: string]: unknown
}
export interface Content {
  date?: Date
  author?: Author
  heading?: Heading
  copy?: Copy
  textColor?: TextColor
  ctas: CTAs
  background?: Background
  [k: string]: unknown
}
export interface CTA {
  text: Text
  url: URL
  color: Color
  size: Size
  [k: string]: unknown
}
export interface Background {
  color?: BackgroundColor
  src?: BackgroundImage
  desktopPositionX: BackgroundImageDesktopPositionX
  desktopPositionY: BackgroundImageDesktopPositionY
  mobilePositionX: BackgroundImageMobilePositionX
  mobilePositionY: BackgroundImageMobilePositionY
  [k: string]: unknown
}
