/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Optional heading text
 */
export type HeadingText = string
export type Text = string
export type URL = string
/**
 * @maxItems 50
 */
export type Links = Link[]

export interface ListTabButtons {
  headingText?: HeadingText
  links?: Links
  [k: string]: unknown
}
export interface Link {
  text: Text
  url: URL
  [k: string]: unknown
}
