/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ActionLink = string
export type ActionText = string
export type ChoseTextAlignment = 'left' | 'right' | 'center'
export type Font = string
export type HrefTag = string
export type Image1 = string
export type AltTag = string
export type Text = string
/**
 * @maxItems 50
 */
export type ListArray = Link[]
export type BorderGap = string
export type HasBorderOnListCard = boolean
export type ImageRadius = string
export type ImageWidth = string
export type CardSize = string
export type MarginOfListContainer = string
export type NumberOfColumns = number
export type NumberOfColumnsInMobileView = number
export type NumberOfRowsToBeRenderedInMobileView = number
export type LabelForShowMoreButton = string
export type LabelForShowMoreButtonWhenYouWantToToggleItToBeHidden = string
export type TextColor = string

/**
 * List images in pages
 */
export interface ListImage {
  list: ListArray
  borderGap?: BorderGap
  hasBorder?: HasBorderOnListCard
  imageRadius?: ImageRadius
  imageWidth?: ImageWidth
  cardSize?: CardSize
  listContainerMargin?: MarginOfListContainer
  numberOfColumns?: NumberOfColumns
  numberOfColumnsMobile?: NumberOfColumnsInMobileView
  renderedRows?: NumberOfRowsToBeRenderedInMobileView
  showMoreText?: LabelForShowMoreButton
  hideText?: LabelForShowMoreButtonWhenYouWantToToggleItToBeHidden
  textColor?: TextColor
  [k: string]: unknown
}
export interface Link {
  actionLink?: ActionLink
  actionText?: ActionText
  textAlignment: TextAlignment
  font?: Font
  href: HrefTag
  image: Image
  text: Text
  [k: string]: unknown
}
/**
 * Text Alignment Options
 */
export interface TextAlignment {
  sort: ChoseTextAlignment
  [k: string]: unknown
}
export interface Image {
  src?: Image1
  alt?: AltTag
  [k: string]: unknown
}
