/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type HeadingText = string
export type Image1 = string
export type AlternativeText = string
/**
 * Select "Eager" when this section appears above the fold.
 */
export type ImageLoadingStrategy = 'lazy' | 'eager'
/**
 * @minItems 1
 */
export type Dates = [Date, ...Date[]]
export type DateText = string
/**
 * @minItems 1
 */
export type Readings = [Reading, ...Reading[]]
export type Title = string
/**
 * @minItems 1
 */
export type AlternativeReadings = [AlternativeReading, ...AlternativeReading[]]
export type Title1 = string
/**
 * @minItems 1
 */
export type HolyDays = [HolyDay, ...HolyDay[]]
export type Title2 = string
export type Date1 = string
export type Season = string
export type Year = string
export type Calendar =
  | 'select'
  | 'revisedCommonLectionary'
  | 'romanCatholicLectionary'

/**
 * Liturgical Calendar Search section
 */
export interface LiturgicalCalendarSearch {
  headingText?: HeadingText
  image?: Image
  imageLoadingStrategy: ImageLoadingStrategy
  dates?: Dates
  [k: string]: unknown
}
export interface Image {
  src: Image1
  alt?: AlternativeText
  [k: string]: unknown
}
export interface Date {
  dateText?: DateText
  readings?: Readings
  altReadings?: AlternativeReadings
  holyDays?: HolyDays
  date?: Date1
  season?: Season
  year?: Year
  calendar?: Calendar
  [k: string]: unknown
}
export interface Reading {
  title?: Title
  [k: string]: unknown
}
export interface AlternativeReading {
  title?: Title1
  [k: string]: unknown
}
export interface HolyDay {
  title?: Title2
  [k: string]: unknown
}
