/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Location = string
export type Date = string
export type Description = string
export type Address = string
export type MapIframeCode = string
export type Host = string
export type Email = string
export type Phone = string
export type Website = string
export type EventName = string

/**
 * Information for the Live Events Details page
 */
export interface LiveEventsDetailsInfo {
  about: About
  directions: Directions
  contact: Contact
  [k: string]: unknown
}
export interface About {
  location: Location
  date: Date
  description: Description
  [k: string]: unknown
}
export interface Directions {
  address: Address
  mapIframeCode: MapIframeCode
  [k: string]: unknown
}
export interface Contact {
  host: Host
  email: Email
  phone: Phone
  website: Website
  eventName: EventName
  [k: string]: unknown
}
