/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * @minItems 1
 */
export type Cards = [Card, ...Card[]]
export type Image1 = string
export type AlternativeText = string
export type ColorOverlay = 'black' | 'maroon' | 'darkGrey'
export type Heading = string
export type Date = string
export type StartDate = string
export type Description = string
export type State = string
export type LinkText = string
export type LinkURL = string

/**
 * Grid of Live Events
 */
export interface LiveEventsGrid {
  cards: Cards
  [k: string]: unknown
}
export interface Card {
  image: Image
  colorOverlay: ColorOverlay
  heading: Heading
  date: Date
  startDate: StartDate
  description: Description
  state: State
  linkText: LinkText
  linkUrl: LinkURL
  [k: string]: unknown
}
export interface Image {
  src: Image1
  alt?: AlternativeText
  [k: string]: unknown
}
