/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Image = string
export type AlternativeText = string
export type ColorOverlay = 'black' | 'maroon' | 'darkGrey'
export type Sponsor = string
export type Title = string
export type Tagline = string
export type Location = string
export type Date = string

/**
 * Header banner for the Live Events Details page
 */
export interface LiveEventsDetailsBanner {
  backgroundImage: BackgroundImage
  colorOverlay: ColorOverlay
  text: Text
  [k: string]: unknown
}
export interface BackgroundImage {
  src: Image
  alt?: AlternativeText
  [k: string]: unknown
}
export interface Text {
  sponsor: Sponsor
  title: Title
  tagline: Tagline
  location: Location
  date: Date
  [k: string]: unknown
}
