/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type BackgroundImageSrc = string
export type Image = string
export type AlternativeLabel = string
export type Text = string
export type Url = string
export type Color =
  | 'default'
  | 'neutralDark'
  | 'neutralLight'
  | 'naked'
  | 'important'
export type Text1 = string
export type Url1 = string
export type Color1 =
  | 'default'
  | 'neutralDark'
  | 'neutralLight'
  | 'naked'
  | 'important'
export type Text2 = string
export type Url2 = string
export type Color2 =
  | 'default'
  | 'neutralDark'
  | 'neutralLight'
  | 'naked'
  | 'important'
  | 'myScoreBlue'
  | 'myScoreOrange'
export type Text3 = string
export type Url3 = string
export type Color3 =
  | 'default'
  | 'neutralDark'
  | 'neutralLight'
  | 'naked'
  | 'important'
  | 'myScoreBlue'
  | 'myScoreOrange'
/**
 * Select "Eager" when this section appears above the fold.
 */
export type ImageLoadingStrategy = 'lazy' | 'eager'

/**
 * Banner displayed on My Score page
 */
export interface MyScoreBanner {
  backgroundImage?: BackgroundImage
  logo: Logo
  linkOne?: LinkOne
  linkTwo?: LinkTwo
  buttonOne?: ButtonOne
  buttonTwo?: ButtonTwo
  imageLoadingStrategy: ImageLoadingStrategy
  [k: string]: unknown
}
export interface BackgroundImage {
  src?: BackgroundImageSrc
  [k: string]: unknown
}
export interface Logo {
  src: Image
  alt: AlternativeLabel
  [k: string]: unknown
}
export interface LinkOne {
  text: Text
  url: Url
  color: Color
  [k: string]: unknown
}
export interface LinkTwo {
  text: Text1
  url: Url1
  color: Color1
  [k: string]: unknown
}
export interface ButtonOne {
  text: Text2
  url: Url2
  color: Color2
  [k: string]: unknown
}
export interface ButtonTwo {
  text: Text3
  url: Url3
  color: Color3
  [k: string]: unknown
}
