/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Heading = string
export type Text = string
export type URL = string
export type Color =
  | 'default'
  | 'neutralDark'
  | 'neutralLight'
  | 'naked'
  | 'important'
export type Size = 'small' | 'medium' | 'large'
export type ProductCount = number
export type Sort =
  | 'discount_desc'
  | 'name_asc'
  | 'name_desc'
  | 'orders_desc'
  | 'price_asc'
  | 'price_desc'
  | 'release_desc'
  | 'score_desc'
export type SearchTerm = string
/**
 * Tip: For categories, use: category-{level}. For collections, use: productClusterIds.
 */
export type Key = string
/**
 * Tip: For categories, use: id. For collections, use: id
 */
export type Value = string
export type Facets = Facet[]

/**
 * Add product list carousel using intelligent search queries.
 */
export interface ProductListQuery {
  heading: Heading
  cta?: CallToAction
  productQuery?: Products
  [k: string]: unknown
}
export interface CallToAction {
  text?: Text
  url?: URL
  color: Color
  size: Size
  [k: string]: unknown
}
export interface Products {
  first?: ProductCount
  sort?: Sort
  term?: SearchTerm
  selectedFacets?: Facets
  [k: string]: unknown
}
export interface Facet {
  key: Key
  value: Value
  [k: string]: unknown
}
