/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Heading = string
export type TagCount = number

/**
 * Adds product tag links. Only use on PDP.
 */
export interface ProductTags {
  heading: Heading
  count: TagCount
  [k: string]: unknown
}
