/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Heading = string
export type ProductCount = number
/**
 * Change cross selling types
 */
export type ProductType = 'category' | 'buy' | 'view'

/**
 * Add cross selling product list to your Product Detail Page.
 */
export interface ProductListCrossSellPDP {
  heading: Heading
  numberOfItems: ProductCount
  kind: ProductType
  [k: string]: unknown
}
