/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Text = string
export type BackgroundColor = 'transparent' | 'white' | 'lightGrey'
export type FontFamily = "'futura-pt', sans-serif" | "'open-sans', sans-serif"
/**
 * Use either a hex code or an rgb value
 */
export type TextColor = string
export type TextAlignment =
  | 'start'
  | 'left'
  | 'right'
  | 'center'
  | 'justify'
  | 'match-parent'
export type HasLineRunningThroughText = boolean

/**
 * Rich text section
 */
export interface RichText {
  text?: Text
  backgroundColor?: BackgroundColor
  font?: FontFamily
  textColor?: TextColor
  textAlignment?: TextAlignment
  hasLine?: HasLineRunningThroughText
  [k: string]: unknown
}
