/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type HeadingText = string
export type Image1 = string
export type AlternativeText = string
/**
 * Select "Eager" when this section appears above the fold.
 */
export type ImageLoadingStrategy = 'lazy' | 'eager'

/**
 * Scripture Search section
 */
export interface ScriptureSearch {
  headingText?: HeadingText
  image: Image
  imageLoadingStrategy: ImageLoadingStrategy
  [k: string]: unknown
}
export interface Image {
  src: Image1
  alt?: AlternativeText
  [k: string]: unknown
}
