/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Height in pixels
 */
export type Height = number
/**
 * Add a divider line to the spacer
 */
export type Divider = boolean

/**
 * Spacer used to add space between sections
 */
export interface Spacer {
  height: Height
  divider?: Divider
  [k: string]: unknown
}
