/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Select which type of page this section is appearing on.
 */
export type PageType = 'landing' | 'state' | 'national'

/**
 * UI to search for state and festival lists
 */
export interface StateAndFestivalLists {
  page: PageType
  [k: string]: unknown
}
