/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * It is necessary to add this component to the global components or to the page where you want to use trustPilot so that the scripts can be applied and the trustpilot blocks can be rendered.
 */
export interface TrustPilotScript {
  [k: string]: unknown
}
