/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * @minItems 2
 * @maxItems 2
 */
export type Cards = [Card, Card]
export type Image1 = string
export type AlternativeText = string
export type Heading = string
export type Copy = string
export type Text = string
export type URL = string
export type Color =
  | 'default'
  | 'neutralDark'
  | 'neutralLight'
  | 'naked'
  | 'important'
export type Size = 'small' | 'medium' | 'large'
/**
 * Select "Eager" when this section appears above the fold.
 */
export type ImageLoadingStrategy = 'lazy' | 'eager'

/**
 * Two cards displayed on home page
 */
export interface TwoCards {
  cards: Cards
  imageLoadingStrategy: ImageLoadingStrategy
  [k: string]: unknown
}
export interface Card {
  image: Image
  heading?: Heading
  copy?: Copy
  cta: CallToAction
  [k: string]: unknown
}
export interface Image {
  src: Image1
  alt?: AlternativeText
  [k: string]: unknown
}
export interface CallToAction {
  text?: Text
  url: URL
  color: Color
  size: Size
  [k: string]: unknown
}
