/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Image = string
export type AlternativeText = string
export type HeadingText = string
export type Copy = string
/**
 * Select "Eager" when this section appears above the fold.
 */
export type ImageLoadingStrategy = 'lazy' | 'eager'

/**
 * Worship Planning section
 */
export interface WorshipPlanningHeader {
  header: Header
  imageLoadingStrategy: ImageLoadingStrategy
  [k: string]: unknown
}
export interface Header {
  bannerImage: BannerImage
  headingText?: HeadingText
  copy?: Copy
  [k: string]: unknown
}
export interface BannerImage {
  src: Image
  alt?: AlternativeText
  [k: string]: unknown
}
